name: attendance_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  fonts:
      - family: SFProDisplay
        fonts:
        - asset: assets/SFPRODISPLAYBOLD.OTF
        - asset: assets/SFPRODISPLAYREGULAR.OTF
        - asset: assets/SFPRODISPLAYMEDIUM.OTF
      - family: Musicalina
        fonts:
        - asset: assets/musicalina.ttf
      - family: BroadwayMusical
        fonts:
        - asset: assets/Broadway-Musical.ttf

  uses-material-design: true